### ISSUE TITLE
Release a version based on Realm JS v6 (Realm Core v6)

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-studio#1170]
## Todo
- [x] Await release date
- [x] Merge https://github.com/realm/realm-studio/pull/1279

As this was previously released on the beta channel, we should:
- [ ] Delete [the beta channel branch](https://github.com/realm/realm-studio/tree/channel/beta).
- [ ] Update the beta auto-update S3 .yml files ([win](https://static.realm.io/downloads/realm-studio/beta.yml), [mac](https://static.realm.io/downloads/realm-studio/beta-mac.yml), [linux](https://static.realm.io/downloads/realm-studio/beta-linux.yml)) to point beta releases to the latest release ([win](https://static.realm.io/downloads/realm-studio/latest.yml), [mac](https://static.realm.io/downloads/realm-studio/latest-mac.yml), [linux](https://static.realm.io/downloads/realm-studio/latest-linux.yml)).

**Comment by kraenhansen** [comment]
Upgrading Realm JS is blocked by https://github.com/realm/realm-js/issues/2274

**Comment by kraenhansen** [comment]
I verified that the fix for https://github.com/realm/realm-js/issues/2406 solves the issue and the latest pre-release version of Realm JS (4.0.0-alpha.2) passes all Realm Studio tests.

For pre-release versions of Realm Studio using Core 6, please see https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-studio/detail/PR-1218/6/artifacts (internal for Realm employees)

I believe we're ready to ship a version of Realm Studio for Core 6 as soon as the Realm JS 4.0.0 release is out.

**Comment by RealmBot** [comment]
➤ Kræn Hansen commented:

[~brian.munkholm] what's the reason this got closed? I don't consider this closed until we have released a Studio on the latest release channel from an official Realm JS v4 release.

**Comment by RealmBot** [comment]
➤ Brian Munkholm commented:

Because the main integration work captured by the title was done and this issue kept being moved from sprint to sprint :-)
None of the other SDKs has an issue to do the final release, but we can either reopen or just make another "Make GA release w. Core6"?
