### ISSUE TITLE
MongoDB ObjectID Support

### ISSUE THREAD

**Issue by RealmBot** [realm/realm-studio#1251]
## Todo
- [ ] Adding a property to an existing class:
  - [ ] Add the `"object id"` as a primitive type: https://github.com/realm/realm-studio/blob/master/src/ui/RealmBrowser/primitives.ts#L19, which enables it to be selected when adding a property to a Realm file.
- [ ] Creating an object:
  - [ ] Add a new component to [the collection of controls when creating an object](https://github.com/realm/realm-studio/tree/master/src/ui/RealmBrowser/Content/CreateObjectDialog/types).
  - [ ] Update [`generateInitialValue` ](https://github.com/realm/realm-studio/blob/master/src/ui/RealmBrowser/Content/CreateObjectDialog/index.tsx#L83) to generate an appropriate initial value.
  - [ ] Update the [`TypeControl`](https://github.com/realm/realm-studio/blob/master/src/ui/RealmBrowser/Content/CreateObjectDialog/types/TypeControl.tsx) component to display the new control component.
- [ ] Showing values in the table:
  - [ ] Add a new component to [the collection of cell type components](https://github.com/realm/realm-studio/tree/master/src/ui/RealmBrowser/Content/Table/types) or reuse the StringCell component.
  - [ ] Add a case for `"object id"` in the [`Cell`](https://github.com/realm/realm-studio/blob/master/src/ui/RealmBrowser/Content/Table/Cell.tsx) component, to show the new component.
  - [ ] Update [`parsers`](https://github.com/realm/realm-studio/blob/master/src/ui/RealmBrowser/parsers.ts#L82-L100) to parse from string to a BSON ObjectId.
- [ ] Update the [`AddClassModal`](https://github.com/realm/realm-studio/blob/master/src/ui/RealmBrowser/AddClassModal/AddClassModal.tsx) to include the `"object id"` as primary key type (defaulting to the `_id` property name).
- [ ] Update the [schema exporter](https://github.com/realm/realm-studio/tree/master/src/services/schema-export) and [its tests](https://github.com/realm/realm-studio/tree/master/src/services/schema-export/tests/models).

**Comment by kraenhansen** [comment]
I have prepared [a branch](https://github.com/realm/realm-studio/tree/mongodb-schema-property-types) based on an older commit on `master` which has not been upgraded to Electron 8. This is needed to enable using Realm JS `v10-alpha.5` - as that does not have the NAPI changes merged in (yet). I've also cherry-picked [the commit that removes ROS & Realm Cloud](https://github.com/realm/realm-studio/commit/44b31bdf6605b88bddcb9d3e604526c3e10f6500).
