### ISSUE TITLE
Prepare repository for MongoDB Realm Studio

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#1276]
Prepare the next major version of Realm Studio.

Ideally we would like release this on the latest channel, but that would upgrade existing users of Realm Studio to an experience which would have features removed (related to ROS and Realm Cloud).

To ensure that this next major version does not interfere with existing users of Realm Studio we have (at least) four options:

1. Fork the entire project / repository (and the [studio-releases](https://github.com/realm/studio-releases) [deployment](http://studio-releases.realm.io/)).
1. [Change the S3 bucket](https://github.com/realm/realm-studio/blob/master/package.json#L88-L91) to which we publish artifacts (and auto-update .yml files) and either change the [studio-releases](https://github.com/realm/studio-releases) server to read from both buckets or deploy another variant of [studio-releases](https://github.com/realm/studio-releases), which reads only from this new bucket.
1. Since the repository is no longer private, we might be able to publish (and auto-update) directly [via GitHub](https://www.electron.build/configuration/publish.html#githuboptions) as an alternative to option 3.
1. Release on a separate channel (ex `mongodb`): This will allow us to reuse CI and the studio-releases server, but it will effectively make releasing according to semantic versioning for mongodb releases impossible.

## ToDo
This following assumes want to do the least amount of initial work (effectively picking the fourth option).

### First iteration
* [x] Create a release channel branch (like https://github.com/realm/realm-studio/tree/channel/beta) with the `mongodb` pre-release identifier prepended the package version.

On the new `channel/mongodb` branch:

* [x] [Rename the app to "MongoDB Realm Studio"](https://github.com/realm/realm-studio/blob/master/package.json#L3) as well as [its bundle id](https://github.com/realm/realm-studio/blob/master/package.json#L15) to enable users to experience the difference and run both "legacy Realm Studio" (v3) and the new "MongoDB Realm Studio" side-by-side on the same machine.
* [ ] Verify that renaming gives a new install path and acts as two separate apps in regards to [the singleton lock](https://github.com/realm/realm-studio/blob/master/src/main/Application.ts#L128).

### Second iteration (enabling a nice link to download the latest version from the MongoDB channel)
* [ ] [Perform an initial release](https://github.com/realm/realm-studio/blob/master/docs/RELEASING.md) to allow iterating on the [studio-releases](https://github.com/realm/studio-releases) server.
* [ ] Update the [studio-releases](https://github.com/realm/studio-releases) server to lookup the latest release based off the .yml file on S3, allowing downloads from any channel (not just latest as its currently the case). This will enable distribution of download links to the latest mongodb version via http://studio-releases.realm.io/mongodb/download/mac-dmg.

### Third iteration (should probably have its own issue for the future)
Once we deem it acceptable to upgrade existing users of Realm Studio to MongoDB Realm Studio (once the Realm Cloud is offline?)

* [ ] Merge in the `mongodb` release channel into master and release on the latest channel (without the `mongodb` pre-release id).

**Comment by kraenhansen** [comment]
There's still a few outstanding tasks on this that we might want to complete in the nearish future.
