### ISSUE TITLE
As a developer I would like to edit a cell of type "bool"

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#29]
### TODO

- [ ] Change the visual appearance to a checkbox.
- [ ] Allow the user to "reset" the value to a `nil` state, if the field is optional.
- [ ] Propagate a change of value to the Realm object.
