### ISSUE TITLE
As a developer I would like to edit a cell of type "int"

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#30]
### TODO

- [ ] Change the visual appearance to an input field (type="number" and perhaps a pattern and step attribute), when the user clicks the cell.
- [ ] Allow the user to "reset" the value to a `nil` state, if the field is optional.
- [ ] Consider any additional validation that might be needed, as suggested by #3 
- [ ] Propagate a change of value to the Realm object.
