### ISSUE TITLE
As a developer I would like to edit a cell of type "date"

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#33]
### TODO

- [ ] Change the visual appearance to an input field (type="date" or perhaps type="datetime-local"?), when the user clicks the cell.
- [ ] Allow the user to "reset" the value to a `nil` state, if the field is optional.
- [ ] Consider any additional validation that might be needed, as suggested by #3
- [ ] Propagate a change of value to the Realm object.
