### ISSUE TITLE
As a developer I would like to edit a cell of type "data"

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#34]
### TODO

- [ ] When the user clicks a cell of type data, we could display a new window, with
  - [ ] A button to browse a local file to "overwrite" the data.
- [ ] Allow the user to "reset" the value to a `nil` state, if the field is optional.
- [ ] Consider any additional validation that might be needed, as suggested by #3
- [ ] Propagate a change of value to the Realm object.

**Comment by stoneark** [comment]
So this feature is still missing now, right? Will you get it implemented? I think it's a very important and basic feature for a database editor...

**Comment by nirinchev** [comment]
Yes it is not implemented yet (as denoted by the fact the issue is still open). Can you share more information about the use case that you have?

**Comment by stoneark** [comment]
I want to embed a realm database file in the app bundle, providing some static fundamental data. It's helpful if Realm Studio can edit content of binary data column.

**Comment by kraenhansen** [comment]
@stoneark in the current version of Studio you can only add data when creating an object that contains a data field - editing is not yet supported.

How would do you envision this feature? Would you want to select a file from your desktop or perhaps enter a hex / base64 encoded string?

**Comment by stoneark** [comment]
@kraenhansen select a file from local disk is fine for me :)
