### ISSUE TITLE
As a developer I would like to edit a cell of type "single object reference"

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#37]
### TODO

- [ ] Change the visual appearance to open up some sort of ["object selection window"](https://github.com/realm/realm-studio/issues/168) (that can be reused whenever a user is prompted to select an object of a specific type), where an object can be selected from all objects of the class expected by the field.
- [ ] Create an issue on extending this feature with an ability to filter the list of objects.
- [ ] Allow the user to "reset" the value to a `nil` state, if the field is optional.
- [ ] Consider any additional validation that might be needed, as suggested by #3
- [ ] Propagate a change of value to the Realm object.
