### ISSUE TITLE
As a developer I would like to edit a cell of type "list of object references"

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#38]
This is how the Mac browser displays a draggable list of objects:

![skaermbillede 2017-08-15 kl 15 26 08](https://user-images.githubusercontent.com/1243959/29317858-2716f7d2-81ce-11e7-817e-45c054b25474.png)

### TODO

- [x] Add an index collumn.
- [x] When clicking a field of this type, open a new window (or navigate the current?) and display rows for each of the referenced objects.
- [x] Allow for the user to drag around the rows to change the order.
- [x] Allow for the user to create a new object or add an existing object of the desired class (possibly using the dialog from #37).
- [x] Allow the user to "reset" the value to a `nil` state, if the field is optional (instead of clicking to open the "list of object references editor")
- [x] Consider any additional validation that might be needed, as suggested by #3 
- [x] Propagate a change of value to the Realm object.
