### ISSUE TITLE
Use node v9 to build

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#668]
## TODO
* [ ] Update `.nvmrc` to use node @ v9
* [ ] Revert the changes made to Dockerfile.releasing and Dockerfile.testing to use the latest `wine-chrome` docker image from `electronuserland/builder`
* [ ] Ensure that Realm Object Server does not depend on realm in version v1.x.x - see https://github.com/realm/realm-object-server-private/issues/874
* [ ] Update keytar to a version that is prebuilt for node @ v9
